# Generated by Django 3.1.7 on 2023-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('PS', 'Posao'), ('SL', 'Slobodan dan')], default='PS', max_length=2),
        ),
    ]
